### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/vertical-ngo#191]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [ ] framework_agreement_requisition
- [ ] framework_agreement_sourcing
- [ ] framework_agreement_sourcing_stock_route_transit
- [ ] logistic_budget
- [ ] logistic_consignee
- [ ] logistic_order
- [ ] logistic_order_donation
- [ ] logistic_order_donation_budget
- [ ] logistic_order_donation_shipment_test
- [ ] logistic_order_donation_transit
- [ ] logistic_order_multicurrency
- [ ] logistic_order_requisition_donation
- [ ] logistic_requisition
- [ ] logistic_requisition_department
- [ ] logistic_requisition_donation
- [ ] logistic_requisition_multicurrency
- [ ] ngo_purchase
- [ ] ngo_purchase_requisition
- [ ] ngo_shipment_plan
- [ ] vertical_ngo
